### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by wltryang** [chromebookdatascience/lecture_notes#2]
Section: What is the start menu?
Changed "star menu" to start menu.

Section: Navigate the menu
Should we change that to navigating the menu?
"Among the icons on the left side of the Chromebook screen, the start menu is a white rimmed circle that is located at the bottom left corner as shown in the image." Seems a bit repetitive.
Maybe highlight the button in the pictures?

**Comment by ykim160** [comment]
Please don't change the setting from claimed to done when I haven't finished the section but thanks for the comments.

**Comment by wltryang** [comment]
Oh my bad I thought it was done.

**Comment by ykim160** [comment]
I changed the issues you mentioned are there any other problems with the current fixes??

**Comment by wltryang** [comment]
Looks good to me.
Again, sorry about before, I'll be more careful next time.
